import {Flex} from "./Flex"
import { StyledPage } from "../styles/StyledPage"
import { StyledMargin } from "../styles/StyledMargin"
import StyledButton from "../styles/StyledButton"
import { StyledLanguageButton } from "../styles/StyledLanguageButton"
import { StyledPageTitle } from "../styles/StyledPageTitle"
import {StyledDiv} from "../styles/StyledDiv"
import {StyledParagraph} from "../styles/StyledParagraph"
import {StyledSpan} from "../styles/StyledSpan"
import {StyledTitle} from "../styles/StyledTitle"
import { DisplayChatsStyle } from "./DIsplayChatsStyle"
import { ProfileChat } from "./PrifileChat"
import { ContentChat } from "./ContentChat"
import {NoConversationStyle} from "./NoConversationStyle";
import { ContentConversationPage } from "./ContentConversationPage";
import { ButtonConversation } from "./ButtonConversation"
import { ConversationPageStyle } from "./ConversationPageStyle"
import { ConversationNoData } from "./ConversationNoData"
import { ChatsDisplay } from "./ChatsDisplay"
import { ButtonForChats } from "./ButtonForChats"
import { BlockDiv } from "./BlockDiv"
export {Flex, StyledPage, StyledMargin, StyledButton, StyledLanguageButton, StyledPageTitle, StyledDiv, StyledParagraph, StyledSpan, StyledTitle, ContentConversationPage,ConversationPageStyle,ButtonConversation,DisplayChatsStyle, ProfileChat, ContentChat, NoConversationStyle,ConversationNoData,ChatsDisplay, ButtonForChats, BlockDiv}